# Generated by Django 4.2.7 on 2023-11-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование группы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TimeField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count_buy', models.IntegerField(verbose_name='Количесвто покупок')),
                ('author', models.CharField(max_length=255, verbose_name='автор')),
                ('year_of_publication', models.IntegerField(verbose_name='Год издания')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательсво')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.category')),
                ('rev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.reviews')),
            ],
        ),
    ]
