# Generated by Django 4.2.7 on 2023-11-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.reviews'),
        ),
    ]
