# Generated by Django 4.2.7 on 2023-11-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.reviews'),
        ),
    ]
