# Generated by Django 4.2.7 on 2023-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='photos/book-preload.svg', upload_to='media/photos/', verbose_name='Изображение'),
        ),
    ]
