# Generated by Django 4.2.7 on 2023-12-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rev',
        ),
        migrations.AddField(
            model_name='reviews',
            name='article_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
