# Generated by Django 4.2.7 on 2023-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_reviews_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.CharField(max_length=80),
        ),
    ]
