# Generated by Django 4.2.7 on 2023-12-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_reviews_article_id_alter_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='978-5-38-924083-4', max_length=255, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.IntegerField(default=8, verbose_name='Возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=1760, verbose_name='Количесвто страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='size',
            field=models.CharField(default='21.5x14.5x8.8', max_length=255, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='book',
            name='type_of_cover',
            field=models.CharField(default='Твердый переплёт', max_length=255, verbose_name='Тип обложки'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.IntegerField(default=2010, verbose_name='Вес'),
        ),
    ]
