# Generated by Django 4.2.7 on 2024-01-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug_author',
            field=models.SlugField(default=None, max_length=255, verbose_name='slug_author'),
        ),
    ]
