# Generated by Django 4.2.7 on 2024-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_slug_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug_author',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug_author'),
        ),
    ]
