# Generated by Django 4.2.7 on 2024-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_author_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_slug_URL',
            field=models.SlugField(max_length=255, verbose_name='author_slug_URL'),
        ),
    ]
