# Generated by Django 4.2.7 on 2024-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_author_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.CharField(max_length=1024, verbose_name='Комментарий'),
        ),
    ]
