# Generated by Django 4.2.7 on 2024-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_slug_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug_author',
        ),
        migrations.AddField(
            model_name='book',
            name='author_slug_URL',
            field=models.SlugField(default=0, max_length=255, verbose_name='author_slug_URL'),
        ),
    ]
