# Generated by Django 4.2.7 on 2024-01-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_book_slug_author_book_author_slug_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_slug_URL',
        ),
    ]
